### ISSUE TITLE
Activate Travis CI

### ISSUE THREAD

**Issue by arnfinn** [SKDE-Felles/qmongr#1]
`.travis.yml`file I (@arnfinn) have used before:

```
language: r
sudo: false
cache: packages
warnings_are_errors: true

matrix:
  include:
    - os: linux
      dist: xenial
      r: release
      env: 
        - DIST=xenial
        - AFTER_JOBS=true
    - os: linux
      dist: xenial
      r: devel
      env: 
        - DIST=xenial
        - AFTER_JOBS=false
    - os: windows
      r: release
      env: 
        - DIST=windows
        - AFTER_JOBS=false
  allow_failures:
    - os: windows

env:
  global:
    - _R_CHECK_TESTS_NLINES_=0

repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - covr
  - lintr
  - roxygen2
  - pkgdown

script:
  - R CMD build .
  - R CMD check *tar.gz

after_script:
  - |
    if [[ "$AFTER_JOBS" == "true" ]] && [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      Rscript -e 'lintr::lint_package()'
    fi

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'roxygen2::roxygenise()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages                         # Specify the gh-pages deployment method
  skip_cleanup: true                      # Don't remove files
  github_token: $GITHUB_TOKEN             # Set in travis-ci.org dashboard
  local_dir: docs                         # Deploy the docs folder
  on:
    branch: master
    condition: "$AFTER_JOBS = true"
    type: push

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always 
```

See for instance https://github.com/SKDE-Felles/SKDEr/blob/master/.travis.yml

**Comment by arnfinn** [comment]
`.travis.yml`file I (@arnfinn) have used before:

```
language: r
sudo: false
cache: packages
warnings_are_errors: true

matrix:
  include:
    - os: linux
      dist: xenial
      r: release
      env: 
        - DIST=xenial
        - AFTER_JOBS=true
    - os: linux
      dist: xenial
      r: devel
      env: 
        - DIST=xenial
        - AFTER_JOBS=false
    - os: windows
      r: release
      env: 
        - DIST=windows
        - AFTER_JOBS=false
  allow_failures:
    - os: windows

env:
  global:
    - _R_CHECK_TESTS_NLINES_=0

repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - covr
  - lintr
  - roxygen2
  - pkgdown

script:
  - R CMD build .
  - R CMD check *tar.gz

after_script:
  - |
    if [[ "$AFTER_JOBS" == "true" ]] && [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      Rscript -e 'lintr::lint_package()'
    fi

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'roxygen2::roxygenise()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages                         # Specify the gh-pages deployment method
  skip_cleanup: true                      # Don't remove files
  github_token: $GITHUB_TOKEN             # Set in travis-ci.org dashboard
  local_dir: docs                         # Deploy the docs folder
  on:
    branch: master
    condition: "$AFTER_JOBS = true"
    type: push

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always 
```

See for instance https://github.com/SKDE-Felles/SKDEr/blob/master/.travis.yml
